apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ercot-visualizer.serviceAccountName" . }}
  labels:
    {{- include "ercot-visualizer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
